/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.arpablue.arpaimage.winui.dlg;

import com.arpablue.arpaimage.core.Beholder;
import com.arpablue.arpaimage.core.Painter;
import com.arpablue.arpaimage.paintobj.InteractiveSquare;

/**
 *
 * @author AugLaptop
 */
public class ItemMenuDlg extends javax.swing.JDialog {
    private int mX = 0;
    private int mY = 0;
    public ItemMenuDlg( java.awt.Frame parent ) {
        super(parent,false);
        initComponents();
    }

    /**
     * Creates new form ItemMenuDlg
     */
    public ItemMenuDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mPanel = new javax.swing.JPanel();
        mDivs = new javax.swing.JLabel();
        mTopPanel = new javax.swing.JPanel();
        mCloseBtn = new javax.swing.JLabel();
        mDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        mPanel.setMinimumSize(new java.awt.Dimension(50, 100));
        mPanel.setPreferredSize(new java.awt.Dimension(100, 200));

        mDivs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/arpablue/arpaimage/imgs/icons/divs.png"))); // NOI18N
        mDivs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        mDivs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divsClick(evt);
            }
        });

        mTopPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mCloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/arpablue/arpaimage/imgs/icons/closeIcon.png"))); // NOI18N
        mCloseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeDlg(evt);
            }
        });

        mDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mDragMouseDragged(evt);
            }
        });
        mDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mDragMousePressed(evt);
            }
        });

        javax.swing.GroupLayout mTopPanelLayout = new javax.swing.GroupLayout(mTopPanel);
        mTopPanel.setLayout(mTopPanelLayout);
        mTopPanelLayout.setHorizontalGroup(
            mTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mTopPanelLayout.createSequentialGroup()
                .addComponent(mDrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mCloseBtn))
        );
        mTopPanelLayout.setVerticalGroup(
            mTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(mDrag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mCloseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mPanelLayout = new javax.swing.GroupLayout(mPanel);
        mPanel.setLayout(mPanelLayout);
        mPanelLayout.setHorizontalGroup(
            mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mPanelLayout.createSequentialGroup()
                .addComponent(mDivs)
                .addGap(0, 66, Short.MAX_VALUE))
        );
        mPanelLayout.setVerticalGroup(
            mPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mPanelLayout.createSequentialGroup()
                .addComponent(mTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mDivs)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void divsClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divsClick
        InteractiveSquare image = new InteractiveSquare();
        Beholder.setActive(image);
        Painter.getLayers().add(image);
    }//GEN-LAST:event_divsClick

    private void closeDlg(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeDlg
        this.setVisible(false);
    }//GEN-LAST:event_closeDlg

    private void mDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDragMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation( x - mX, y - mY );
    }//GEN-LAST:event_mDragMouseDragged

    private void mDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mDragMousePressed
        mX = evt.getX();
        mY = evt.getY();
    }//GEN-LAST:event_mDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemMenuDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemMenuDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemMenuDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemMenuDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ItemMenuDlg dialog = new ItemMenuDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
       dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel mCloseBtn;
    private javax.swing.JLabel mDivs;
    private javax.swing.JLabel mDrag;
    private javax.swing.JPanel mPanel;
    private javax.swing.JPanel mTopPanel;
    // End of variables declaration//GEN-END:variables
}
